package com.holaho.intern.shared.dto.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.util.List;

@Data
public class CreateUserRequest {

    @NotBlank(message = "Email không được để trống")
    @Email(message = "Email không hợp lệ")
    private String email;

    @NotBlank(message = "Họ tên không được để trống")
    private String fullName;

    // Password is auto-generated by backend if not provided, or optional here.
    private String password;

    private String phone;

    private String address;

    @Size(min = 1, message = "Phải chọn ít nhất 1 vai trò")
    private List<String> roleCodes;

    // Optional fields for specific roles
    private Long departmentId;
    private String title; // for MENTOR
    private String studentCode; // for INTERN
    private String university; // for INTERN
    private String major; // for INTERN
}
