package com.holaho.intern.shared.dto.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.util.List;

@Data
public class CreateUserRequest {

    @NotBlank(message = "Email khÃƒÂ´ng Ã„â€˜Ã†Â°Ã¡Â»Â£c Ã„â€˜Ã¡Â»Æ’ trÃ¡Â»â€˜ng")
    @Email(message = "Email khÃƒÂ´ng hÃ¡Â»Â£p lÃ¡Â»â€¡")
    private String email;

    @NotBlank(message = "HÃ¡Â»Â tÃƒÂªn khÃƒÂ´ng Ã„â€˜Ã†Â°Ã¡Â»Â£c Ã„â€˜Ã¡Â»Æ’ trÃ¡Â»â€˜ng")
    private String fullName;

    // Password is auto-generated by backend if not provided, or optional here.
    private String password;

    private String phone;

    private String address;

    @Size(min = 1, message = "PhÃ¡ÂºÂ£i chÃ¡Â»Ân ÃƒÂ­t nhÃ¡ÂºÂ¥t 1 vai trÃƒÂ²")
    private List<String> roleCodes;

    // Optional fields for specific roles
    private Long departmentId;
    private String title; // for MENTOR
    private String studentCode; // for INTERN
    private String university; // for INTERN
    private String major; // for INTERN
}

