package com.holaho.intern.shared.enums;

public enum ApplicationStatus {
    DRAFT, SUBMITTED, REVIEWING, SCREENING, INTERVIEWING, NEEDS_REVISION, APPROVED, REJECTED, CONTRACT_SENT, CONTRACT_SIGNED, INTERNING, COMPLETED, TERMINATED
}

