public enum NotificationType {
    MEETING_CREATED,
    MEETING_UPDATED,
    MEETING_CANCELLED,
    MEETING_REMINDER,
    SYSTEM,
    EMAIL,
    TASK,
    APPLICATION,
    WEEKLY_REPORT,
    INTERNSHIP_COMPLETED,
    INTERNSHIP_TERMINATED,
    OTHER
}

